services:
  - type: web
    name: smartclassroommanagamentsystem
    env: python
    region: frankfurt  # or oregon, singapore, etc.
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
